[server]
address = "0.0.0.0"
headless = true
maxUploadSize = 20

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#137A65"
backgroundColor = "#FAFCFA"
secondaryBackgroundColor = "#EFF4F0"
textColor = "#183A32"
font = "sans serif"
